apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-demo
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: itm-team
  system: itm-support-portal
  definition: |
    openapi: 3.0.0
    info:
      title: Mock API
      version: 1.0.0
    servers:
      - url: "http://mock-svc.apiopskong.svc:8080"
        description: "Integration API Server for ITM"
      - url: "https://apis-integraciones.tigo.com.gt/users"
        description: "Integration API Server for ITM"
    paths:
      /users:
        get:
          summary: Obtiene la lista de usuarios
          responses:
            '200':
              description: Respuesta exitosa
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string    
        post:
          summary: Crea un nuevo usuario
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
          responses:
            '201':
              description: Usuario creado exitosamente
            '400':
              description: Error en la solicitud
      /products:
        get:
          summary: Obtiene la lista de productos
          responses:
            '200':
              description: Respuesta exitosa
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        price:
                          type: number
        post:
          summary: Crea un nuevo producto
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                    price:
                      type: number
                  required:
                    - name
                    - price
          responses:
            '201':
              description: Producto creado exitosamente
            '400':
              description: Error en la solicitud
